__title__ = 'pyoslog'
__version__ = '0.3.0'
__description__ = 'Send messages to the macOS unified logging system'
__author__ = 'Simon Robinson'
__author_email__ = 'simon@robinson.ac'
__url__ = 'https://github.com/simonrob/pyoslog'
__copyright__ = 'Copyright (c) 2022 Simon Robinson'
__license__ = 'Apache 2.0'
